### ISSUE TITLE
 Library version handling

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#10]
Please provide a library version handling machinery or at least a version string (primesieve_version)
See for example:
https://www.gnu.org/software/gnulib/manual/html_node/Library-version-handling.html
https://github.com/coreutils/gnulib/blob/master/lib/check-version.c
https://gmplib.org/manual/Useful-Macros-and-Constants.html#index-gmp_005fversion-183

Thanks for your work and your well designed C/C++ API.

**Comment by kimwalisch** [comment]
There are macro version definitions in both ```primesieve.hpp``` and ```primesieve.h```:

```
#define PRIMESIEVE_VERSION "5.4.2"
#define PRIMESIEVE_VERSION_MAJOR 5
#define PRIMESIEVE_VERSION_MINOR 4
#define PRIMESIEVE_VERSION_PATCH 2
```

Please let me know if you still need a version function e.g. ```primesieve_version()```.

**Comment by jgmbenoit** [comment]
I was aware of the macro versions. The aim of the game here is to access to the version against which the library libprimesieve.so was built. Of course this can be useful to print the version at run time, but here we can also use the macro. The essential idea is to check the version of (dynamic) library against the version of the header at compile time. Hence my request.
The scheme suggested by GNULIB [1,2] is very practical and very easy to implement.

[1] https://www.gnu.org/software/gnulib/manual/html_node/Library-version-handling.html
[2] https://github.com/coreutils/gnulib/blob/master/lib/check-version.c

**Comment by kimwalisch** [comment]
I have now implemented a primesieve_version() function: https://github.com/kimwalisch/primesieve/commit/bdbe308de9c2540d3d28c9aeacdf72451717aa38. Hence I am now offering the same functionality as the [GNU GMP library](https://gmplib.org/manual/Useful-Macros-and-Constants.html#index-gmp_005fversion-183) which should be enough for 99% of my users.

**Comment by jgmbenoit** [comment]
The GNU MP library aslo furnishes a gmp_version string.

**Comment by kimwalisch** [comment]
Yes, you are right GMP provides a gmp_version string instead of a gmp_version() function. Personally I prefer using a primesieve_version() function.
