### ISSUE TITLE
Batch mode (output numbers only)?

### ISSUE THREAD

**Issue by rulatir** [kimwalisch/primesieve#102]
This is not a request to implement number theory superpowers. This is just a request to add an option to output **only** the primes and nothing else, for batch processing. `-q` currently does not do that: `primesieve 1 100 -n -q` outputs `Nth prime: 101` instead of just `101`.

**Comment by kimwalisch** [comment]
Thanks for your feedback, I wasn't aware of this issue.

I think that batch processing is important therefore I have changed the behavior of the -q/--quiet option (https://github.com/kimwalisch/primesieve/commit/4981c10e1d3fbdae15a3f2119cccd0039baca582) to your suggestion. I know this is a backwards incompatible change, it will e.g. break the phoronix test suite. However I think it is worth it, so I will likely help fixing the projects that this change will break.

Note that as I have done a release not so long ago, it will take some time before I do another release. So if you want this change immediately, you will have to compile primesieve from source yourself. Also note that my [primecount](https://github.com/kimwalisch/primecount) project also has an --nth-prime option and actually computes the nth prime much faster, more info [here](https://github.com/kimwalisch/primecount#fast-nth-prime-calculation).
