### ISSUE TITLE
I build use msvc and want to use c/c++ api,but somthing wrong with #include path

### ISSUE THREAD

**Issue by tisttsf** [kimwalisch/primesieve#104]
If I follow the capi doc and create file somewhere outside primesieve-master/include folder. It appear
`p1.cpp:1:10: fatal error: primesieve.hpp: No such file or directory
    1 | #include <primesieve.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.`
if I change the code to or else.
```c++
#include "include/primesieve.hpp"
#include <iostream>

int main()
{
    primesieve::iterator it;
    uint64_t prime = it.next_prime();

    // Iterate over the primes below 10^6
    for (; prime < 1000000; prime = it.next_prime())
        std::cout << prime << std::endl;

    return 0;
}
```
It appears 
`In file included from p1.cpp:1:
include/primesieve.hpp:20:10: fatal error: primesieve/iterator.hpp: No such file or directory
   20 | #include <primesieve/iterator.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

How to solve that path error or is there something wrong with my build process?
![捕获](https://user-images.githubusercontent.com/4705133/132977663-676da0e9-1957-4752-84f2-7aeff6d76b2c.PNG)

**Comment by kimwalisch** [comment]
Can you try adding the primesieve include path to the MSVC compiler options:

```
cl /EHsc /O2 /I "...path/to/primesieve-master/include"
```

The reason it failed is that you have not globally installed primesieve and hence the compiler cannot find the primesive headers. This is also explained here https://github.com/kimwalisch/primesieve#microsoft-visual-c, including how to link against the static primesieve.lib library.

Another option that might be easier: Add your ```p1.cpp``` file to the ```primesieve/examples/cpp``` directory, then build primesieve using ```cmake . -DBUILD_EXAMPLES=ON```. This way your program will be automatically compiled using the correct include path and linked against ```primesieve.lib```

**Comment by kimwalisch** [comment]
So if you want to try the solution with putting your cpp file into the ```primesieve/examples/cpp``` directory. The MSVC build commands are (open a Visual Studio Command-Prompt and cd into the primesieve directory):

```
cmake -G "Visual Studio 16 2019" .
cmake --build . --config Release
```

I think I will add this information to C_Examples.md and CPP_Examples.md as it will be helpful, especially for people without in-depth C or C++ knowledge.

**Comment by tisttsf** [comment]
> Another option that might be easier:
> 
> Add your `p1.cpp` file to the `primesieve/examples/cpp` directory, then build primesieve using `cmake . -DBUILD_EXAMPLES=ON`. This way your program will be automatically compiled using the correct include path and linked against `primesieve.lib`. The exact MSVC build commands that you need to run are (open a Visual Studio Command-Prompt and cd into the primesieve directory):
> 
> ```
> cmake -G "Visual Studio 16 2019" -DBUILD_EXAMPLES=ON .
> cmake --build . --config Release
> ```
I can build exe use this method now,thank you!

**Comment by kimwalisch** [comment]
> I can build exe use this method now,thank you!

Great 😊
