### ISSUE TITLE
primesieve_previous_prime: continously return UINT64_MAX

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#11]
Please provide an example involving primesieve_previous_prime
Thanks in advance,
Jerome

**Comment by kimwalisch** [comment]
Here you are:
https://github.com/kimwalisch/primesieve/blob/master/examples/c/previous_prime.c

**Comment by jgmbenoit** [comment]
It rocks well !
I guess that I was confused by the hint_stop parameter: in my mind it was an upper bound.
Anyway, thanks a lot.

**Comment by jgmbenoit** [comment]
Just a comment with a  suggestion. If in the provided example we replace the lower bound 1000 by 2, naming if we run backward over prime numbers not exceeding 2000, the loop gets infinite because for 2 primesieve_previous_prime returns UINT64_MAX. It can be easily caught. Nevertheless, if for 2 primesieve_previous_prime returns 1 instead, and for 1 UINT64_MAX, the code keeps simple while it make sense, the number 1 playing a particular role in Number Theory (not a  prime, but not a composite number either, and so forth)

**Comment by kimwalisch** [comment]
> Nevertheless, if for 2 primesieve_previous_prime returns 1 instead

I like your idea, I even had the same idea some time ago because I ran into the same issue in my [primecount](https://github.com/kimwalisch/primecount) project where I had to write a wrapper around ```primesieve::previous_prime()```:

```
class ReversePrimeIterator
{
public:
  ReversePrimeIterator(int64_t stop, int64_t start) :
    iter_(stop, start),
    prime_(stop)
  { }
  int64_t previous_prime()
  {
    if (prime_ <= 2)
      return -1;
    prime_ = iter_.previous_prime();
    return prime_;
  }
private:
  primesieve::iterator iter_;
  int64_t prime_;
};
```

The other possibility would be to use 0 instead of 1. Currently I am slightly in favor of using 0 because I think it is easier for users to understand that this is a dummy element and not a prime.

**Comment by kimwalisch** [comment]
In the PARI/GP computer algebra system they also use 0:

```
Function: precprime
Section: number_theoretical
C-Name: precprime
Prototype: G
Help: precprime(x): largest pseudoprime <= x, 0 if x<=1.
Description:
 (gen):int        precprime($1)
Doc: finds the largest pseudoprime (see
 \tet{ispseudoprime}) less than or equal to $x$. $x$ can be of any real type.
 Returns 0 if $x\le1$. Note that if $x$ is a prime, this function returns $x$
 and not the largest prime strictly smaller than $x$. To rigorously prove that
 the result is prime, use \kbd{isprime}.                                     
```

**Comment by kimwalisch** [comment]
And Dana Jacobson's Math-Prime-Util also returns 0:

```
=== prev_prime ===

$n = prev_prime($n);

Returns the prime preceding the input number (i.e. the largest
prime that is strictly less than the input). 0 is returned if the
input is 2 or lower.
```

**Comment by kimwalisch** [comment]
Implemented previous_prime() returns 0 if input <= 2: https://github.com/kimwalisch/primesieve/commit/41d7549c91966a83571cfa05e1b6782ef44c9fe7

**Comment by jgmbenoit** [comment]
Returning 0 is also definitely more programming oriented. So now we can implement aesthetic backward loops.
