### ISSUE TITLE
Help confirm Windows bug with Intel big.LITTLE CPUs (>= 12th Gen.)

### ISSUE THREAD

**Issue by kimwalisch** [kimwalisch/primesieve#129]
If you have an Intel big.LITTLE CPU (>= 12th Gen.) can you please run the command below on your Windows PC and post the output in this thread:

```bash
primesieve --cpu-info

# Output on my Windows 11 PC
12th Gen Intel(R) Core(TM) i5-12600K
Logical CPU cores: 16
L1 cache size: 48 KiB
L2 cache size: 1280 KiB
L3 cache size: 20 MiB
L1 cache sharing: 2 threads
L2 cache sharing: 2 threads
L3 cache sharing: 16 threads

```

(If primesieve is not yet installed on your PC, you can install it using: ```winget install primesieve```)

If a CPU has both performance and efficiency CPU cores primesieve usually detects the cache sizes of the efficiency CPU cores because using these cache sizes provides the best overall multi-threading performance. However on my Windows PC with an i5-12600 Intel Alder Lake CPU primesieve is not able to detect the cache sizes of the efficiency CPU cores because Windows only reports the cache sizes of the performance CPU cores (at least on my PC). On current Intel big.LITTLE CPUs the performance CPU cores have 48 KiB L1 data cache per core whereas the efficiency CPU cores have 32 KiB L1 data cache per core.

I think this is a Windows bug (caused ```GetLogicalProcessorInformationEx``` from kernel32.dll) and I need feedback from other Windows users to know if they are experiencing the same issue. Funnily this bug was not present on my Windows 10 PC at the beginning of this year, so this bug could have been introduced by a recent Windows update. Another possible explanation would be that the bug was triggered when I disabled/re-enabled the efficiency CPU cores in BIOS for testing.

# Bug also present in WSL2

This bug can also be triggered from the Windows Subsystem for Linux using my i5-12600 CPU. In the command below only the L1 data cache size of the performance CPU cores is reported.

```
for i in {0..64}; do cat /sys/devices/system/cpu/cpu$i/cache/index0/size 2>/dev/null; done | uniq
48 KiB
```

**Comment by catb0t** [comment]
I can confirm this doesn't exist in 22H2, but didn't test in a prior release. And yes, it affects WSL2, still sadly
