### ISSUE TITLE
L1_DCACHE_SIZE at execution time

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#13]
Please determine CACHE sizes at execution time rather than at build time. The rational behind is to provide a computer independent library for distribution.

**Comment by kimwalisch** [comment]
This is a good idea but it is technically not feasible without using horrible hacks i.e. you cannot do it in plain C/C++ and you will have to provide many different implementations for all kinds of operating systems and CPU architectures.

Below are my get L1_DCACHE_SIZE hacks I devised over the past years:

https://gist.github.com/kimwalisch/8223975
https://gist.github.com/kimwalisch/a34bf029a492cba4112f

I could combine both versions above and get the L1_DCACHE_SIZE at runtime on most systems but I think these hacks should not be used in production code. And I don't want to depend on another library to get the L1_DCACHE_SIZE.

Taking into consideration both the advantages (minor speed up on some systems) and disadvantages (horrible hacks) I believe that I should leave everything as is.

**Comment by jgmbenoit** [comment]
Hello:

On 18/10/15 01:20, Kim Walisch wrote:
> This is a good idea but it is technically not feasible without using
> horrible hacks i.e. you cannot do it in plain C/C++ and you will have
> to provide many different implementations for all kinds of operating
> systems and CPU architectures.
> 
> Below are my get L1_DCACHE_SIZE hacks I devised over the past years:
> 
> https://gist.github.com/kimwalisch/8223975 
> https://gist.github.com/kimwalisch/a34bf029a492cba4112f
> 
> I could combine both versions above and get the L1_DCACHE_SIZE at
> runtime on most systems but I think these hacks should not be used in
> production code. And I don't want to depend on another library to get
> the L1_DCACHE_SIZE.

The code in configure.ac seems not highly complicated, at least for Linux box:

cat /sys/devices/system/cpu/cpu0/cache/index0/size

On the other hand, getconf and sysctl simple shell tools.

I guess it is getting more complicated on non Linux boxes.


> 
> Taking into consideration both the advantages (minor speed up on some
> systems) and disadvantages (horrible hacks) I believe that I should
> leave everything as is.

For distribution, the library may be box independent.

Thanks,
Jerome


> 
> — Reply to this email directly or view it on GitHub
> <https://github.com/kimwalisch/primesieve/issues/13#issuecomment-148960205>.
>
> 
-- 
Jerome BENOIT, Ph.D. | jgmbenoit-at+rezozer*dot_net
http://www.rezozer.net/
