### ISSUE TITLE
sieve  is not best match on 13gen cpu?

### ISSUE THREAD

**Issue by chopin1998** [kimwalisch/primesieve#134]
i got a intel 13700K,

i run primesieve 1e12, without other paramets it take ~ 11.7sec,

but when i add -s32, it take only ~9.9sec

![image](https://user-images.githubusercontent.com/643792/227098486-072d2ac8-b131-4cb8-9872-803e854e36fb.png)

**Comment by kimwalisch** [comment]
Yes, you are right.

However, it is simply very difficult to know the best sieve size for every CPU (see here: https://github.com/kimwalisch/primesieve/blob/master/src/api.cpp#L149 and here: https://github.com/kimwalisch/primesieve/blob/master/src/Erat.cpp#L101). What primesieve does is use a CPU sieve array size that works well across all different CPU types. The current setting is e.g. optimal for AMD CPUs and Apple CPUs, for Intel CPUs it also optimal but only when using a single thread.

The L2 cache of current Intel CPUs has multi-threading performance issues. I think that Intel will eventually fix those issues in a future CPU generation at which point the current primesieve settings should perform best.

**Comment by marioroy** [comment]
Something to try is factoring out the hyper-threads on the p-cores. Unable to verify, I'm not sure which CPU IDs are the performance cores ([0-7] or [0,2,4,6,8,10,12,14]), the hyper-threads ([8-15] or [1,3,5,7,9,11,13,15]). The e-cores are likely [16-23]. 

On Linux, one can apply CPU affinity using the `taskset` utility. Below is an attempt to factor out the hyper-threads. One of these will run faster [0-7] or [0,2,4,...] for determining the physical core CPU IDs. 

```bash
taskset -c 0-7,16-23 primesieve --threads=16 1e12
taskset -c 0-7,16-23 primesieve --threads=16 -s32 1e12

taskset -c 0,2,4,6,8,10,12,14,16-23 primesieve --threads=16 1e12
taskset -c 0,2,4,6,8,10,12,14,16-23 primesieve --threads=16 -s32 1e12
```

Similarly, one can run primesieve on the p-cores only or e-cores.

```bash
# run on p-cores + hyper-threads
taskset -c 0-15 primesieve --threads=16 1e12

# run on p-cores excluding hyper-threads
# select the one that ran fastest above [0-7] or [0,2,4,...]
taskset -c 0-7 primesieve --threads=8 1e12
taskset -c 0,2,4,6,8,10,12,14 primesieve --threads=8 1e12

# run on e-cores only
taskset -c 16-23 primesieve --threads=8 1e12
```
