### ISSUE TITLE
Use "" include guards instead of <> : is it wise ?

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#15]
I think you should keep the <> brackets in the `<SRC>/include/primesieve.h'  as this header is meant to be installed system wide. Guessing: to short cut it at built time, appropriate -I<PATH> may be passed.

**Comment by kimwalisch** [comment]
I actually think using <> is a bug. I posted a question about that here:
https://groups.google.com/d/msg/comp.lang.c++.moderated/7NdqryhO6xM/tfpT5yZQDwAJ

but unfortunately I did not get a good answer. I had a look at many header files inside /usr/include and most used "" for the particular case when you have a header which includes more headers inside of similar named directory.

The code below (even though nobody would ever write such code) would fail using <> if there are two versions of primesieve installed, one in /usr and another one in /usr/local:

```
// file: user_code.cpp
#include </usr/include/primesieve.h>
``` 

```
// file: /usr/include/primesive.h

// the include below includes /usr/local/include/primesieve/primesieve_iterator.h
// instead of /usr/include/primesieve/primesieve_iterator.h
#include <primesieve/primesieve_iterator.h>
``` 

What do you think about this somehow constructed case?

**Comment by jgmbenoit** [comment]
Hello Kim:

On 29/10/15 21:28, Kim Walisch wrote:
> I actually think using <> is a bug.

No, it is not a bug but feature.

 I posted a question about that here:
> https://groups.google.com/d/msg/comp.lang.c++.moderated/7NdqryhO6xM/tfpT5yZQDwAJ

It is not a direct C/C++ issue, but rather a filesystem hierarchy issue: see below.
>
>  but unfortunately I did not get a good answer. I had a look at many
> header files inside /usr/include and most used "" for the particular
> case when you have a header which includes more headers inside of
> similar named directory.

This issue is not a democratic issue but a technical issue, if not a scientific one.
I would add, on which kind of box did you have a look ? on a Windows box ?
on a messy lab box ? on a sane Debian box ?

> 
> The code below (even though nobody would ever write such code) would
> fail using <> if there are two versions of primesieve installed, one
> in /usr and another one in /usr/local:
> 
> |// file: user_code.cpp #include </usr/include/primesieve.h> |

Forget this code: the /usr/include is installation specific:
this part is supposed to be part of the configuration of the compilers.
Far a scrap code, otherwise, "" will be more appropriate here.


> 
> |// file: /usr/include/primesive.h
> 
> // the include below includes
> /usr/local/include/primesieve/primesieve_iterator.h // instead of
> /usr/include/primesieve/primesieve_iterator.h #include
> <primesieve/primesieve_iterator.h> |

This choice is expected as files /usr/local is meant to shortcut /usr : this a default.
You are dealing here with the Filesystem Hiearchy Standard ,

 https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
 http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/Linux-Filesystem-Hierarchy.html ,

not with directly C/C++  (a decent configuration of compilers (and other tools) may
follows the FHS).

In short, the box must be clean up: remove the material in /usr/ or in /usr/local to avoid
interference. Note the keeping a sane box is not that easy as it looks, especially on the 
long term. (I will add that Debian is meant for that, and it is very efficient. Debian
manage /usr via apt-get and its friends, but let the root to  manage /usr/local by hand :
it is  a very good idea not to interfere with apt-get unless you want  to experience a messy box).

> 
> What do you think about this somehow constructed case?

You may have a look to the libtool manual, in particular:
https://www.gnu.org/software/libtool/manual/libtool.html#Library-tips

> 
> — Reply to this email directly or view it on GitHub
> <https://github.com/kimwalisch/primesieve/issues/15#issuecomment-152308814>.

hth,
Jerome

>
> 
-- 
Jerome BENOIT, Ph.D. | jgmbenoit-at+rezozer*dot_net
http://www.rezozer.net/

**Comment by kimwalisch** [comment]
> I would add, on which kind of box did you have a look ? on a Windows box ?
> on a messy lab box ? on a sane Debian box ?

On my Fedora 22 box. As written in my post in found the examples below:

```
cat /usr/include/gssapi.h | grep include 
#include <gssapi/gssapi.h> 

cat /usr/include/ruby.h | grep include 
#include "ruby/ruby.h" 
```

Note that I just installed ruby on my Ubuntu 15.10 box (I guess on debian it's the same) and it also uses:

```
cat /usr/include/ruby-2.1.0/ruby.h | grep include 
#include "ruby/ruby.h" 
```

But of course you're the expert and I trust you more than the ruby devs. Also using <> instead of "" will fix the issue with ugly full path names in graphs generated by doxygen. Hence I will update both ```primesieve.h``` and ```primesieve.hpp```.

**Comment by jgmbenoit** [comment]
Hello Again.

On 29/10/15 22:45, Kim Walisch wrote:
> I would add, on which kind of box did you have a look ? on a Windows
> box ? on a messy lab box ? on a sane Debian box ?
> 
> On my Fedora 22 box. As written in my post in found the examples
> below:
> 
> |cat /usr/include/gssapi.h | grep include #include <gssapi/gssapi.h>
> 


This sounds correct.

> 
> cat /usr/include/ruby.h | grep include #include "ruby/ruby.h" |
> 
> Note that I just installed ruby on my Ubuntu 15.10 box (I guess on
> debian it's the same) and it also uses:
> 
> |cat /usr/include/ruby-2.1.0/ruby.h | grep include #include
> "ruby/ruby.h" |


This is a bug.

> 
> But of course you're the expert

Indeed :-)


 and I trust you more than the ruby
> devs. Also using <> instead of "" will fix the issue with ugly full
> path names in graphs generated by doxygen. Hence I will update both
> |primesieve.h| and |primesieve.hpp|.
> 
> — Reply to this email directly or view it on GitHub
> <https://github.com/kimwalisch/primesieve/issues/15#issuecomment-152337349>.
>
> 
-- 
Jerome BENOIT, Ph.D. | jgmbenoit-at+rezozer*dot_net
http://www.rezozer.net/
