### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by Porsche9II** [kimwalisch/primesieve#19]
Hi, very nice project and it works just fine - but unfortunately my use for it is limited because mostly I need dynamic linking instead of static linking...

**Comment by kimwalisch** [comment]
What operating system are you using?

On Unix-like OSes (Linux, Mac OS X) by default a shared and static libprimesieve are built! So on Unix-like OSes if you link using -lprimesieve you are linking against the shared libprimesieve.

On Windows when you compile using MSVC you are right: only a static library will be built. But on Windows you can also build primesieve using Cygwin/MinGW and then it should build both a shared and static primesieve library.

**Comment by Porsche9II** [comment]
Hi Kim,

thank you for your fast reply.

Yes, I need to build it with VS 2013 32bit since I do not have access to
Cygwin/MinGW on my company PC.

Will try to compile it at home at the weekend and see if the Cygwin/MinGW
32 bit DLLs will work in my VS 2013 environment.

Anyhow, great work and great library - well done!

Matt

**Comment by Porsche9II** [comment]
Hi Kim,

How would you build your DLL with cygwin? Like this?

https://blogs.oracle.com/sanaulla/entry/building_dlls_using_cygwin

When I want to use functions from this cygwin DLL for my VS2013 DLL it does not seem to work...

I get an error message saying that the compiler cannot find the function...

Probably I misunderstood your first post... Do you think it's possible to use functions from a cygwin DLL in a VS2013 DLL?

Matt

**Comment by kimwalisch** [comment]
> When I want to use functions from this cygwin DLL for my VS2013 DLL it does not seem to work...

Yes, after thinking about it I don't think it can work because the primesieve DLL has been compiled using a different compiler (MinGW GCC) than your code (MSVC).

It would work if you compiled your code with MinGW as well. But this is most likely not an option for you.
