### ISSUE TITLE
Failed tests with Visual Studio 2015 update 3

### ISSUE THREAD

**Issue by SChernykh** [kimwalisch/primesieve#20]
If I compile primesieve with VS2015 update 3, it fails tests:

pi(x) : Prime-counting function test
pi(10^1)  = 4           OK
pi(10^2)  = 25          OK
pi(10^3)  = 168         OK
pi(10^4)  = 1229        OK
pi(10^5)  = 9592        OK
pi(10^6)  = 78498       OK
pi(10^7)  = 664579      OK
pi(10^8)  = 6426034     ERROR

primesieve error: test failed!

Adding "-d2SSAOptimizer-" to compiler's command line fixes the issue, so I see two alternatives here:
1) There is undefined behavior somewhere in primesieve's code, and the new SSA optimizer in VS2015 update 3 generates different code there (20% chance).
2) There is a bug in the new SSA optimizer in VS2015 update 3 (80% chance).

Optimizer bug is very likely, but it's still worth investigating for what exactly causes the issue: optimizer bug or undefined behavior.

**Comment by SChernykh** [comment]
I've tried command line option "-d2UndefIntOverflow-" as advised here: https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer/

It didn't help, so it's more likely to be optimizer bug.

**Comment by kimwalisch** [comment]
Thanks for letting me know, I will test myself this weekend.

**Comment by kimwalisch** [comment]
So here are my findings using ```VS2015 Update 3```:

* The bug exists in both ```primesieve-5.6.0``` and in the very latest ```primesieve-5.7.0``` under development. I guess the bug exist in older versions as well.
* The bug goes away if I remove the ```/openmp``` flag for building. 
* The bug also goes away if I build primesieve using ```/O1``` instead of ```/O2```.

My conclusion is that the combination of flags ```/O2``` ```/openmp``` is broken in ```VS2015 Update 3```. This does not come as a surprise to me because Microsoft does not really case about OpenMP since they are still stuck at version 2.5 from 2005.

I will send a bug report to Microsoft. In the meantime I recommend Mingw-w64 (with GCC) for building primesieve on Windows. Or if you don't care about multi-threading you can remove the following part from ```Makefile.msvc```:

```
#-----------------------------------------------------------------------------
# Add /openmp if MSVC supports OpenMP
#-----------------------------------------------------------------------------

!IF ([$(CXX) /openmp /c src\msvc_compat\has_openmp.cpp /Fonul > nul] == 0)
CXXFLAGS = $(CXXFLAGS) /openmp
!ELSE
NO_OPENMP = true
!ENDIF
```

**Comment by kimwalisch** [comment]
From the MS Visual Studio website https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer/:

> you can confirm it’s caused by the new optimizer by using the following undocumented flag to disable it: -d2SSAOptimizer-

When I add this ```-d2SSAOptimizer-``` flag to disable the new optimizer primesieve passes its test suite without an errors:

```
C:\Users\kim\Documents\GitHub\primesieve>primesieve --test
pi(x) : Prime-counting function test
pi(10^1)  = 4           OK
pi(10^2)  = 25          OK
pi(10^3)  = 168         OK
pi(10^4)  = 1229        OK
pi(10^5)  = 9592        OK
pi(10^6)  = 78498       OK
pi(10^7)  = 664579      OK
pi(10^8)  = 5761455     OK
pi(10^9)  = 50847534    OK
pi(10^10) = 455052511   OK

Sieving the primes within [10^12, 10^12+2^32]
100%
Prime count: 155428406  OK
Sieving the primes within [10^13, 10^13+2^32]
100%
Prime count: 143482916  OK
Sieving the primes within [10^14, 10^14+2^32]
100%
Prime count: 133235063  OK
Sieving the primes within [10^15, 10^15+2^32]
100%
Prime count: 124350420  OK
Sieving the primes within [10^16, 10^16+2^32]
100%
Prime count: 116578809  OK
Sieving the primes within [10^17, 10^17+2^32]
100%
Prime count: 109726486  OK
Sieving the primes within [10^18, 10^18+2^32]
100%
Prime count: 103626726  OK
Sieving the primes within [10^19, 10^19+2^32]
100%
Prime count: 98169972   OK

Sieving the primes within [10^15, 10^15+10^11] randomly
Remaining chunk: 0
Prime count: 2895317534 OK

All tests passed successfully!
```

So this is clearly a bug in Visual Studio's new optimizer.

**Comment by SChernykh** [comment]
I'm sure now it's a compiler bug. "/openmp" shouldn't make a single-threaded test fail at all, so it's some combination of code and compilation keys which make it fail.

Judging on my experience, such bug report will be low priority since MS programmers will have to look for a needle in a haystack. Bugs in compiler get fixed quickly when bug report is provided with no more than 20-50 lines of code which reproduce the issue. I'll take the latest primesieve code and investigate a bit more.

**Comment by kimwalisch** [comment]
I found a first hint, the primesieve version below has been compiled using the new optimizer and some good old ```std::cout``` debugging:

```
C:\Users\kim\Documents\GitHub\primesieve>primesieve 1e7 1e8
Sieve size = 32 kilobytes
Threads    = 4
0%PrimeSieve::sieve(), 10000000, 140695696310341
PrimeSieve::sieve(), 1, 100000000
SieveOfEratosthenes(), 10000000, 140695696310341, 11861521, 9999990, 10983031
SieveOfEratosthenes(), 7, SieveOfEratosthenes(), 20, 11861521, 3444, 0, 983041
100000000, 10000, 0, 983041
SieveOfEratosthenes(), 20, 10000, 100, 0, 983041
100%
^C
```

The value ```140695696310341``` represents the stop number and should be < 10^8. Now we need to investigate this happened. The stop number is normally passed on from  ParallelPrimeSieve to PrimeSieve. I will add some ```std::cout``` debugging statements to ParallelPrimeSieve as well...

**Comment by SChernykh** [comment]
So I managed to create a very small repro. Just 3 files and around 70 lines of code. The problem is in ParallelPrimeSieve::align - it doesn't compile correct sometimes.

**Comment by kimwalisch** [comment]
Awesome! Thanks a lot!

I also managed (independently) to identify ```ParallelPrimeSieve::align()``` as being responsible for the bug. This is definitely a compiler bug. I am quite happy that we identified the bug quickly because now I can release ```primesieve-5.7.0``` this weekend as planned.

By the way, I guess we can even simplify your ``` a very small repro``` using the align method from ```primesieve-5.6.0``` which does not use the ```add_overflow_safe()``` function:

```C++
// primesieve-5.6.0
uint64_t ParallelPrimeSieve::align(uint64_t n) const
{
  if (n == start_)
    return start_;
  n = std::min(n + 32 - n % 30, stop_);
  return n;
}
```

**Comment by kimwalisch** [comment]
This is a MSVC 2015 compiler bug that will hopefully be fixed with the next MSVC udapte.

**Comment by SChernykh** [comment]
Microsoft patched Visual Studio 2015 last week and this bug was fixed.
