### ISSUE TITLE
Detect supported but not default C++11 compiler, CMake requirement too strict

### ISSUE THREAD

**Issue by spworley** [kimwalisch/primesieve#27]
GCC 4.8 supports C++11  but it's not on by default, it needs the -std=c++11 flag.  CMake properly detects that this GCC supports C++11 but when it tries to build it does not  succeed since the -std=c++11 flag is not added on the commandline.

I fixed this in the CMakeList.txt file by adding:
```
SET( GCC_COMPILE_FLAGS "-std=c++11")
SET( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} ${GCC_COMPILE_FLAGS}" )
```
There is probably a more elegant or preferred method to do this with Cmake, but this worked.

Also, the CMakelIst.txt has a cmake_minimum_required(VERSION 3) at the top. This seems too strict, since changing it to VERSION 2.8 worked fine with my default CMake 2.8 install. 

Ubuntu 14.04 defaults to  CMake 2.8 and GCC 4.8, which is why I hit these two minor hiccups.

**Comment by kimwalisch** [comment]
Hi,

As you can see I am using the following code in ```CMakeLists.txt``` to detect C++11:

```CMake
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

Normally this automatically adds ```-std=c++11```or ```-std=gnu++11```to the compiler flags. So I guess that gcc-4.8 does not fully support C++11 and therefore the cmake command fails. I have personally tried gcc-4.9, gcc-5.4, gcc-6.3 and it works fine with these compiler versions.

> Also, the CMakelIst.txt has a cmake_minimum_required(VERSION 3) at the top. This seems too strict, since changing it to VERSION 2.8 worked fine with my default CMake 2.8 install.

I chose to require cmake >= 3.1 because the above C++11 detection code is new in cmake 3.1.

**Comment by kimwalisch** [comment]
Actually gcc-4.8 works fine, I am testing using g++-4.8 in my .travis.yml. So it is cmake that is causing the compilation issue on your system. Installing CMake >= 3.1 on your system will fix your compilation issue.

**Comment by spworley** [comment]
Perfect and reasonable explanation, so my issues are a non-issue.

I'm learning a lot from your project. Your algorithms, C++ implementation, documentation, API, and packaging are all supremely polished and solid, so it's been very rewarding to study. 
Thanks!
