### ISSUE TITLE
CLI on macOS ignores -t/--threads

### ISSUE THREAD

**Issue by LosBunkos** [kimwalisch/primesieve#28]
Always uses 1 thread; compiled using basic instructions

**Comment by kimwalisch** [comment]
Hi,

This is because the Clang compiler provided by Apple has OpenMP (multi-threading) disabled. In order to compile primesieve with multi-threading on macOS I suggest you use the GCC compiler instead:

```bash
brew install gcc

CXX=g++-6 cmake .
make -j
```

**Comment by kimwalisch** [comment]
primesieve now uses C++11 threads instead of OpenMP. Multi-threading now also works on macOS using Apple Clang.

**Comment by LosBunkos** [comment]
That's great; I couldn't get brew to link g++. 
The new version works as expected, thanks.
