### ISSUE TITLE
Please add 6 cores option in the GUI.

### ISSUE THREAD

**Issue by Vinvin20** [kimwalisch/primesieve#35]
Thanks !

**Comment by kimwalisch** [comment]
> Please add 6 cores option in the GUI.

Yes, I will add it in the next release.

For my curiosity:

* Why do you want this?
* Are you trying to test hyper-threading vs. no hyper-threading on a hexa-core CPU?

**Comment by Vinvin20** [comment]
I have an Intel 4930K (overclocked to 4 GHz) : https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-4930K+%40+3.40GHz
The CPU has 6 cores.
I would like to investigate a bit 6 threads vs 12 threads.
But I think to users of CPUs how has 3 cores (some AMD some years ago).

Some Screen shots 8 threads and 12 threads :

![capture d ecran 2017-08-16 16 26 12](https://user-images.githubusercontent.com/6450503/29368327-b413e22c-829f-11e7-858b-0c5eaa5f2337.png)
![capture d ecran 2017-08-16 16 25 09](https://user-images.githubusercontent.com/6450503/29368328-b4886566-829f-11e7-9f3a-11bbaed5eefb.png)

**Comment by kimwalisch** [comment]
OK, thanks.

I will take some time though before I do the next release.

**Comment by Vinvin20** [comment]
No problem. Thanks !
You do a great work !

**Comment by kimwalisch** [comment]
Implemented with commit: https://github.com/kimwalisch/primesieve/commit/45dc1afc1e21a0d25616ff56fc6836ea2f80b37f
