### ISSUE TITLE
It does not save the primes into a txt file (or any file for that matter)

### ISSUE THREAD

**Issue by BED822** [kimwalisch/primesieve#5]
I would like to have the primes that it checked to be saved into a text file for personal use.

**Comment by kimwalisch** [comment]
You can easily save the primes using the command-line version of primesieve.

```
# Windows
> primesieve.exe 1000 > primes.txt

# Unix-like OSes
$ ./primesieve 1000 > primes.txt
```

**Comment by BED822** [comment]
How do i use the command line version, assuming i downloaded the .zip file?

**Comment by kimwalisch** [comment]
I guess you are using Windows? If so click the Start button and in the search field type cmd and open it. That's the Windows Command Prompt. Now navigate to the directory (using the cd command) containing the primesieve executable and run it using:

```
# Windows
> primesieve.exe 1000 --print > primes.txt
```
