### ISSUE TITLE
I would like to have the primes that it checked to be saved into a text file for personal use.

### ISSUE THREAD

**Issue by BED822** [kimwalisch/primesieve#6]
I would like to have the primes that it checked to be saved into a text file for personal use.
I decompressed the .zip file, but the "cmd" command below does not work. It says the exe does not exist.
> primesieve.exe 1000 --print > primes.txt

**Comment by kimwalisch** [comment]
You need to use the cd command to navigate to the directory containing the primesieve executable.

**Comment by BED822** [comment]
How do i use the cd command?

**Comment by kimwalisch** [comment]
Use google to find out!?
