### ISSUE TITLE
/usr/bin/ld: cannot find -lprimesieve

### ISSUE THREAD

**Issue by gowtham-munukutla** [kimwalisch/primesieve#64]
I'm on a Linux machine and I followed the official process of installing from the source and exporting LD_LIBARARY_PATH variables in my fish shell.

I tried the example problem of primesieve_iterator.c from the C API given. When I try to compile them with 

`gcc prog.c -lprimesieve` 

it says 

`/usr/bin/ld: cannot find -lprimesieve`
`collect2: error: ld returned 1 exit status`

Am I missing something here or can anyone explain what's going wrong? Thank you.

**Comment by gowtham-munukutla** [comment]
I'm using Arch Linux. So I have LD_LIBRARY_PATH.

And this is my `sudo make install` output.

![screenshot from 2018-11-18 16-46-32](https://user-images.githubusercontent.com/17702388/48671643-9df8b280-eb51-11e8-9320-2d8da5170aea.png)

Please let me know if you need any more details.
Thank you.

**Comment by gowtham-munukutla** [comment]
Hey @kimwalisch I figured out a temporary solution. I had to append both `/usr/local/lib` and `/usr/local/lib64` to LD_LIBRARY_PATH which wasn't there before. Now I don't get any `ld` errors.

Please tell if this solution is okay for me moving forward with my work and close the issue. If you have a better solution in mind, please shoot it in here.

**Comment by kimwalisch** [comment]
> Please tell if this solution is okay for me moving forward with my work and close the issue. If you have a better solution in mind, please shoot it in here.

Yes, this is the correct solution for your system (since the primesieve binary is installed to ```/usr/local/lib``` and libprimesieve is installed to ```/usr/local/lib64```).

**Comment by kimwalisch** [comment]
> since the primesieve binary is installed to ```/usr/local/lib````

Actually the primesieve binary is installed to ```/usr/local/bin``` on your system hence the correct way to define the environment variables is:

```fish
# Fish shell
set -x PATH "/usr/local/bin:$PATH"
set -x LD_LIBRARY_PATH "/usr/local/lib64:$LD_LIBRARY_PATH"
```

Note that I have never used the fish shell but according to some googling this seems how to define environment variables.

**Comment by gowtham-munukutla** [comment]
That's exactly what I did in my fish. I sometimes use fish and bash according to my autocomplete needs.
Anyway, thanks a lot dude. Your profile is amazing. You really write highly optimized code. 

Good luck.
