### ISSUE TITLE
I would like to have the primes that it checked to be saved into a text file for personal use.

### ISSUE THREAD

**Issue by BED822** [kimwalisch/primesieve#7]
I would like to have the primes that it checked to be saved into a text file for personal use.
I decompressed the .zip file, but the "cmd" command below does not work. I used the cd command to point to the folder containing the exe, but when i type the command "primesieve.exe 1000 --print > primes.txt" it creates an empty txt file called "primes". There is nothing in it. What i want is a list of primes from 1 to N, but the command only generate an empty file.

**Comment by kimwalisch** [comment]
I tested your command "primesieve.exe 1000 --print > primes.txt" on my WIndows 7 machine, it creates a primes.txt file (not primes file!) with the primes from 0 to 1000. I suggest you first try if the command "primesieve.exe 1000 --print" works, it should print the primes from 0 to 1000 on the screen. If that works you rerun "primesieve.exe 1000 --print > primes.txt". Remember the primes are saved into primes.txt not primes.

**Comment by BED822** [comment]
Oh... i will try tomorrow. Please don't close the issue until i finish it.
