### ISSUE TITLE
pkg-config improvement suggestion

### ISSUE THREAD

**Issue by laolux** [kimwalisch/primesieve#74]
I am happy that you have implemented pkg-config already.
However, I still have a suggestion for improvement.
It would be great if `libdir=${prefix}/lib/@CMAKE_LIBRARY_ARCHITECTURE@` could actually be `libdir=${prefix}/lib64/@CMAKE_LIBRARY_ARCHITECTURE@` or even better have CMAKE decide whether to use lib or lib64.
Thanks a lot!

**Comment by kimwalisch** [comment]
Thanks for reporting this issue.

> ... or even better have CMAKE decide whether to use lib or lib64.

I agree this is the best solution, now I just need to figure out how to do it. I will try to use Google to find someone else's pkg-config file who gets this right...

**Comment by laolux** [comment]
Glad to hear that.
I am afraid I cannot help much. Do not have much experience with CMAKE.
One way I think could work would be to define a cmake variable like `CMAKE_LIBDIR` which defaults to `lib` and which the user can change when invoking `cmake -DCMAKE_LIBDIR=lib64 .`

**Comment by kimwalisch** [comment]
[googletest](https://github.com/fandjelo/googletest/blob/2c19680bf99dbab41f08b4d39f401486d3a74d06/googlemock/cmake/gmock.pc.in#L2) uses the following code:

```
libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
```

This uses lib64 instead of lib on systems where lib does not exist.

This code change would also fix another error related to my current ```libdir=${prefix}/lib/@CMAKE_LIBRARY_ARCHITECTURE@``` that I just found: below libprimesieve is installed to ```/usr/local/lib``` but ```libdir=${prefix}/lib/x86_64-linux-gnu```.

```bash
$ cd primesieve
$ mkdir build
$ cd build
$ cmake ..
$ make -j4

$ sudo make install
-- Installing: /usr/local/lib/libprimesieve.so.9.4.0
-- Up-to-date: /usr/local/lib/libprimesieve.so.9
-- Up-to-date: /usr/local/lib/libprimesieve.so
-- Installing: /usr/local/lib/libprimesieve.a
-- Installing: /usr/local/lib/pkgconfig/primesieve.pc
...

$ cat /usr/local/lib/pkgconfig/primesieve.pc
prefix=/usr/local
libdir=${prefix}/lib/x86_64-linux-gnu
...
```

I will have to check if this change does not break the primesieve debian package.

**Comment by kimwalisch** [comment]
I have fixed the issue by using the same code as [googletest](https://github.com/fandjelo/googletest/blob/2c19680bf99dbab41f08b4d39f401486d3a74d06/googlemock/cmake/gmock.pc.in#L2):

```diff
@@ -1,7 +1,7 @@
prefix=@CMAKE_INSTALL_PREFIX@
-bindir=${prefix}/bin
-libdir=${prefix}/lib/@CMAKE_LIBRARY_ARCHITECTURE@
-includedir=${prefix}/include
+bindir=${prefix}/@CMAKE_INSTALL_BINDIR@
+libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
+includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@

Name: primesieve
Description: Fast C/C++ prime number generator
```

@laolux: Can you please try if it works now on your PC?

**Comment by laolux** [comment]
@kimwalisch: works perfectly! Thanks a lot!

Now everything works great here.
So next question: Do you mind if I try and package it for Fedora? Haven't done official packaging yet, so might take some time.

**Comment by kimwalisch** [comment]
> @kimwalisch: works perfectly! Thanks a lot!

Great to hear :-)

> So next question: Do you mind if I try and package it for Fedora? Haven't done official packaging yet, so might take some time.

At the beginning of 2018 I packaged primesieve for Fedora myself and submitted my package to the Red Hat Bugzilla for review: https://bugzilla.redhat.com/show_bug.cgi?id=1540335. I got some feedback and fixed all the issues pointed out by the reviewers. At the end my reviewers were happy and the primesieve package was ready to be included into Fedora.

But then started the frustrating part of my Fedora package submission. I needed to find a [sponsor](https://fedoraproject.org/wiki/How_to_get_sponsored_into_the_packager_group) for the primesieve package. So I marked my package as ```FE-NEEDSPONSOR``` in the bug tracker but that did not help. Then I searched online for people that are Fedora maintainers for scientific/math packages and contacted one of them privately by email to ask if he was willing to sponsor the primesieve package. Again I got some positive feedback but eventually nothing happened and primesieve was not included into Fedora.

Here is the repo for primesieve Fedora package:

* https://github.com/kimwalisch/primesieve-rpm

Currently this package is at version primesieve-7.0 (whereas the latest release is primesieve-7.4). I stopped updating this package when I could not find a Fedora sponsor.

Hence I suggest not to waste any time creating a new Fedora package for primesieve. You could help trying to find a sponsor for Fedora, this would be highly appreciated. It seems like it is easier to get your package into Fedora if you have good connections and know a few package sponsors.

**Comment by laolux** [comment]
Ah, I see... Thanks for your advice. Sounds pretty frustrating. Well, in this case I guess I will stick to just making rpms for my lab and myself. It sure is more convenient to use rpms across multiple computers than installing from source on each and every one of them. Especially with primesieve, which pretty much built out of the box for me :-)
Great work!
