### ISSUE TITLE
Initialisation of for-loop

### ISSUE THREAD

**Issue by Tiza59** [kimwalisch/primesieve#81]
Hi Kim,
studying your segmented sieve example I suggest to change

int64_t j = multiples[i];
  for (int64_t k = primes[i] * 2; j < segment_size; j += k)
    sieve[j] = false;

to

int64_t k = primes[i] * 2;
  for (int64_t j = multiples[i]; j < segment_size; j += k)
    sieve[j] = false;

as the loop runs over j.
Cheers,
Uwe

**Comment by kimwalisch** [comment]
Hi,

This seems like a good idea, however it does not work since ```j``` is used outside of the for loop in order to compute the next multiple index for the next segment:

```C++
// sieve the current segment
for (std::size_t i = 0; i < primes.size(); i++)
{
  int64_t j = multiples[i];

  for (int64_t k = primes[i] * 2; j < segment_size; j += k)
    sieve[j] = false;

  // store next multiple index for the next segment
  multiples[i] = j - segment_size;
}
```

**Comment by Tiza59** [comment]
Thanks for your fast explanation!
