### ISSUE TITLE
Version 7.5 and Python bindings

### ISSUE THREAD

**Issue by brl0** [kimwalisch/primesieve#82]
First of all, thanks for the great software!

I have updated the version of the software to which the Python bindings are pinned.  I noticed upcoming updates in the change log, so I thought it might be best to wait until you release v7.5 and then pin to that.  If a new release is imminent, I will hold off, otherwise I will pin to current version.

Let me know your thoughts.
Thanks.

**Comment by brl0** [comment]
This issue can probably be closed.  But for now, I'll use it to ask another question...

An outdated version [(5.7.3)](https://github.com/conda-forge/primesieve-feedstock) of this native package is currently installable from conda-forge as shown below.
`conda install -c conda-forge primesieve`

This is in addition to the python version we recently updated that is also available on conda-forge:
`conda install -c conda-forge python-primesieve`

Do you still want to have this native package built and distributed through conda-forge?  If so, I would be happy to attempt to assist.  If not, we can inquire about how to handle deprecating the existing outdated package.

Another option is to attempt to combine the package with the Python bindings... although I am not sure that would be very useful.

@mingwandroid helpfully suggested on [gitter](https://gitter.im/conda-forge/conda-forge.github.io) that this could be built for conda-forge simultaneously with the python package, but with separate outputs, as with this [example](https://github.com/AnacondaRecipes/boost-feedstock/blob/master/recipe/meta.yaml) given.

@kimwalisch - Let me know what you think.

**Comment by kimwalisch** [comment]
Hi Brian,

> Do you still want to have this native package built and distributed through conda-forge?

As the conda-forge python-primesieve package currently does not depend on the conda-forge primesieve package so the latter package is currently not really useful anymore and I doubt many people are installing primesieve this way.

> If so, I would be happy to attempt to assist.

There is another item on my todo list that seems much more important to me. Currently I only offer primesieve-python binary packages (wheels) for Windows. So on other operating systems users have to install a C++ compiler first which can be quite annoying (e.g. installing Xcode on macOS downloads up to 10 GB which can take several hours). I think it would greatly benefit primesieve-python if we would offer binary wheels for more operating systems.

There are 2 options for offering more binary packages:

1) Improve appveyor.yml, add Linux and macOS support. Currently appveyor.yml is already used to build the Windows binary packages. This is the easy option, where we can get quick results.

2) Add Poetry support to primesieve-python. According to this post https://stefanoborini.com/current-status-of-python-packaging Poetry is currently the state of the art for creating Python binary packages. I have not really looked into Poetry yet, so I cannot tell if it is really much better suited than Appveyor.

I would appreciate your help on this item. If we support more operating systems it would also be nice if we could automate uploading the packages to pypi for new releases. I suggest that before you start coding to have a look at both Appveyor and Poetry and then we take a decision which service we will use.

**Comment by brl0** [comment]
Quick disclaimer, I am a beginner and am not an expert, my goal is to help and to learn by doing.  I am happy to help with this, I just don't want to mislead you.

The issues you mentioned are the kinds of problems conda was created to resolve.  I think that you could just instruct users to install via conda rather than via pip.  It would require conda rather than a compiler, but would not need any additional maintenance.

It looks like you are using Travis CI and Appveyor for the native executables, would it be possible to also use them to build the python wheels?  I wonder if Poetry could somehow be tacked onto those to perform the PyPI uploads?  

Actually, now I wonder if it would be possible to do this from the conda-forge builds, that might be ideal.  I'll check into this out of curiosity.

Let me know your thoughts and I can give it a try on whatever is decided.

**Comment by kimwalisch** [comment]
> Let me know your thoughts and I can give it a try on whatever is decided.

Personally I prefer pypi over conda as it has a much wider user base. Many people have never heard of conda. For this reason it is very important to have good pypi support.

Creating binary packages is very tricky. The main issue I see is that e.g. binary packages built on new operating system versions such as Ubuntu 20 do not run on old operating systems such as Ubuntu 14 because many new features from Ubuntu 20 do not exist in Ubuntu 14. However the other way round it works:  binary packages built on Ubuntu 14 will work on Ubuntu 20 because all features from Ubuntu 14 are still present in Ubuntu 20.

For this reason I think that creating binary packages using Travis and Appveyor is potentially dangerous and the binary packages might not work on old operating system versions (though I have not done any research on this).

As Poetry is the state of the art for Python packaging I trust them to build binary packages that will also work on old operating system versions. I also know that using Poetry we can automate uploading the binary packages to pypi. For this reason I think it would be worth trying to add Poetry support to primesieve-python. We could start to e.g. only try to build macOS binary packages (or Linux binary packages if you don't have a Mac) and also try to automatically upload the packages to pypi. If it works well we would in a second phase add support for the other operating systems...

**Comment by brl0** [comment]
I will give Poetry a try to get a better understanding of the workflow.
Your point about older versions of Ubuntu has me wondering if using Docker for the build would make sense.  
I don't have access to a Mac, just Windows and Linux.

I will be going to a conference this weekend, so I may not make much progress until next week.

**Comment by kimwalisch** [comment]
> I will give Poetry a try to get a better understanding of the workflow.

Great!

> Your point about older versions of Ubuntu has me wondering if using Docker for the build would make sense.

Using Docker does not make much sense in my opinion as it causes too much work as we want to build binary packages for many different operating systems and potentially even for different kinds of CPUs. Creating a docker image for each such configuration would be a large amount of work...

> I will be going to a conference this weekend, so I may not make much progress until next week.

Have fun at the conference!

**Comment by brl0** [comment]
Poetry is [out](https://poetry.eustace.io/docs/cli/#build):

> Note that, at the moment, only pure python wheels are supported.

**Comment by brl0** [comment]
I built a Azure pipeline that handles all platforms for Python 36-38.
This can be configured to upload the builds directly.
PR is [here](https://github.com/hickford/primesieve-python/pull/35) on the primesieve-python repo.
