### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by jgmbenoit** [kimwalisch/primesieve#84]
Instead of maintaining a manpage in some format to convert it to a UN*X manpage with an heavy machinery,
why not just maintain a manpage in native manpage-language ?

**Comment by kimwalisch** [comment]
> Instead of maintaining a manpage in some format to convert it to a UN*X manpage with an heavy machinery, why not just maintain a manpage in native manpage-language ?

I am a big fan of markdown as it allows to create nice looking documentation, also the source code looks like an ordinary txt documentation file so you can read it in any text editor you like. For the same reason I find writing man pages in Asciidoc great as it is comparable to markdown, it is dead easy and the source looks like an ordinary txt file.

Why not write the manpage in native manpage-language? I have opened the ```primesieve.1``` manpage in a text editor in the past and frankly it looks scary, I would like to stay out of that trouble...
