### ISSUE TITLE
default threads

### ISSUE THREAD

**Issue by ktprime** [kimwalisch/primesieve#87]
huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e12 
Sieve size = 256 KiB
Threads = 96
100%
Seconds: 12.084
Primes: 37607912018

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e12 -t16
Sieve size = 256 KiB
Threads = 16
100%
Seconds: 22.042
Primes: 37607912018

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e12 -t32
Sieve size = 256 KiB
Threads = 32
100%
Seconds: 11.309
Primes: 37607912018

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e12 -t24
Sieve size = 256 KiB
Threads = 24
100%
Seconds: 14.867
Primes: 37607912018

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e16 -d1e11 -t24
Sieve size = 256 KiB
Threads = 24
100%
Seconds: 8.378
Primes: 2714336584

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e16 -d1e11 
Sieve size = 256 KiB
Threads = 96
100%
Seconds: 8.084
Primes: 2714336584

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e18 -d1e11  
Sieve size = 256 KiB
Threads = 96
100%
Seconds: 15.204
Primes: 2412731214

huangyuanbing@arm-u18:~/primesieve/build$ ./primesieve 1e18 -d1e11 -t24
Sieve size = 256 KiB
Threads = 24
100%
Seconds: 14.242
Primes: 2412731214

**Comment by kimwalisch** [comment]
Thanks for the benchmarks.

The performance using the default number of threads is actually very good. It is impossible to know the ideal number of threads for a specific interval on a specific CPU. It depends on how well the CPU scales which depends on how well the CPU is built/architected. Generally if the CPU scales well then using all CPU cores should be fastest (which is what primesieve does).
