### ISSUE TITLE
Any thoughts on using OpenCL?

### ISSUE THREAD

**Issue by grgcombs** [kimwalisch/primesieve#9]
Would it be advantageous to also parallelize this with OpenCL, and make the GPUs do some work too?

**Comment by kimwalisch** [comment]
Quite a few people have already tried writing an efficient GPU sieve but nobody has achieved a real break through. Currently the fastest GPU sieve on the web is Ben Buhrow's CUDA Sieve of Eratosthenes.

https://sites.google.com/site/bbuhrow/home/cuda-sieve-of-eratosthenes

Generating primes (e.g. storing the primes in an array) is a sequential task so it is very slow on GPUs. Counting primes can be done reasonably efficient on a GPU (though not faster than CPU) but then there are other algorithms for CPUs which can count primes orders of magnitude faster.
