### ISSUE TITLE
Mismatch with "thread" name on AIX

### ISSUE THREAD

**Issue by trex58** [kimwalisch/primesieve#90]
Hi,
Using "thread" instead of "std::thread" on AIX generates a GCC compiler error.
The simple patch below does fix the issue.
```
--- ./src/ParallelSieve.cpp.ORIGIN      2020-06-04 15:54:18 -0500
+++ ./src/ParallelSieve.cpp     2020-06-04 15:54:41 -0500
@@ -58,7 +58,7 @@

 int ParallelSieve::getMaxThreads()
 {
-  int maxThreads = thread::hardware_concurrency();
+  int maxThreads = std::thread::hardware_concurrency();
   return max(1, maxThreads);
 }
```

**Comment by kimwalisch** [comment]
* And using this fix it compiles successfully on AIX? (I cannot test this)
* What GCC version did you use?

**Comment by trex58** [comment]
Yes. This is the only change I made in the source code.

For now, I'm using GCC v8.4 . However, I also could try with GCC v9.3 .
For now also, I've only built yet in 32bit. I'll do in 64bit too soon.

I've made some changes:
- do not build doc and man
- export CXXFLAGS="-pthread"   : required for threading on AIX
- when running threaded tests, LIBPATH must be changed in order to point to pthread version of GCC first:
     export LIBPATH=/opt/freeware/lib/pthread:/opt/freeware/src/packages/BUILD/primesieve-7.5:/opt/freeware/lib:/usr/lib:/lib

All tests are OK.

**Comment by kimwalisch** [comment]
I think this is a GCC bug which only occurs on AIX. And the AIX operating system is not important enough for me to add a workaround for this bug in primesieve. The other build issues you have reported are CMake issues, again I think these issues come from AIX not being well supported by CMake.

So I close this issue as "won't fix".
